### ISSUE TITLE
Failed prop type: Invalid prop `activeComponent` of type `object` supplied to `Feature`, expected `function`

### ISSUE THREAD

**Issue by karolisgrinkevicius** [paralleldrive/react-feature-toggles#180]
```
├─ @paralleldrive/react-feature-toggles@2.0.2
├─ react@16.6.3
└─ styled-components@4.1.1
```

When using `configureFeature` I'm getting annoying warning `Warning: Failed prop type: Invalid prop activeComponent of type object supplied to Feature, expected function.` in case of feature is not enabled.

Source code that I'm using Feature flags in:
```jsx
const StyledDiv= styled.div`
  padding-left: 10px;
`;

const ComponentOrNull = configureFeature(() => null)('demo')(StyledDiv);

export const Copyright = () => (
  <FeatureToggles features={[]}>
     <ComponentOrNull />
  </FeatureToggles>
);
```

**Comment by karolisgrinkevicius** [comment]
@ericelliott thanks for your reply! 

First of all the problem must be somewhere between `styled-components` and feature toggles. `StyledDiv` returns a component as we definitely expect. Please try out `styled-components` and then if you don't get this warning I will create a reproducible repo. Thanks a lot!

**Comment by kennylavender** [comment]
Hello @karolisgrinkevicius,

I looked at this today for a bit, I tried adjusting the Feature components propTypes to see if adding a node or element type might fix it, but neither of those removed the warning. Interestingly PropTypes.object does get rid of the warning but we don't want to accept just any object so I think its best we avoid making that change.

I dug a bit deeper and it seems that styled-components returns a [forwardRef] object, but the prop-types package doesnt have a type that works for [forwardRef]s at the moment, here is the related issue: https://github.com/facebook/prop-types/issues/200

Looks like React mentions that [forwardRef]s are a breaking change of types: https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers

[forwardRef]: https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components

**Comment by karolisgrinkevicius** [comment]
Hi @kennylavender. Thanks for your response. So we just have to wait while `prop-types` problems are being fixed?

**Comment by kennylavender** [comment]
Your welcome. Yup, if/when they push a solution we can look into it again. Closing for now.
