### ISSUE TITLE
Clarifying real-life use-cases in Example

### ISSUE THREAD

**Issue by kennylavender** [paralleldrive/react-feature-toggles#47]
See https://github.com/paralleldrive/react-feature-toggles/pull/44

> Maybe ComingSoonComponent should be called HelpFallbackComponent or something similar, to make it more clear.

> In real use, I usually render entire pages as 404, or render nothing -- both of which users could configure as reusable fallback components that would work everywhere (like featureOr404(), featureOrNothing(), etc... I think the case where you render ComingSoon would be extremely rare. What you might render instead would be an older version of a component, like help404(HelpChatComponent, OldHelpComponent);

**Comment by ericelliott** [comment]
I think this whole section is confusing:

```js
Alternatively, if we want to override the default 404 fallback component for a feature, we can instead specify a different component to display if the feature is disabled.

// help-chat-container.js
import feature404 from './feature-404'
import HelpChatComponent from './help-chat-component';
import ComingSoonComponent from './coming-soon-component';

const help404 = feature404('help-chat');

export default help404(HelpChatComponent, ComingSoonComponent);
```

That feature is not needed. We should delete it.

## Clarify real-world usage

Let's go back to the dreamcode. First, an example of composing the feature availability into root-level components:

```js
const pageHOC = compose(
  withFeatures(initialFeatures)
  hoc1,
  hoc2,
);
```

Then, show how you can configure the component fallback:

```js
import { configureFeature } from 'react-feature-toggles';

const requiresFeature = configureFeature(NotFound);

export default requiresFeature;
```

Then, show how to build a component that requires a specific feature:

```js
import compose from 'lodash/fp/compose';

import requiresFeature from '../HOCs/requiresFeature';
import MyComponent from './my-component';
import pageHOC from `../hocs/page';

export default compose(
  pageHOC, // withFeatures should be in there
  requiresFeature('feature-name'),
  // Optionally, anything special for this page should be here, e.g.,
  // requiresRole('admin')
)(MyComponent);
```
