### ISSUE TITLE
Fix util importing

### ISSUE THREAD

**Issue by ericelliott** [paralleldrive/react-feature-toggles#67]
Importing is currently broken. We should create files in the root directory that refer to the appropriate files in the distribution. We hit that problem trying to use `getIsEnabled`. We had to import it like this:

```
import getIsEnabled from '@paralleldrive/react-feature-toggles/dist/utils/get-is-enabled';
```

**Comment by kennylavender** [comment]
Yes thanks, I was planning on fixing the entire file/folder structure, have just been waiting on #65
