### ISSUE TITLE
Change the feature context in React

### ISSUE THREAD

**Issue by kennylavender** [paralleldrive/react-feature-toggles#77]
Currently `with-features` reduces the features it receives to an array of enabled feature names.

Preferable we will not reduce it down and keep all of the feature data.

This will allow us to use `getEnabled` and `getIsEnabled` on the React features context client side without having to create special functions.

__This is a breaking change to projects that might have manually used the React features context.__

will tackle after #70

**Comment by ericelliott** [comment]
This may not be a good idea.

1. Revealing all the feature data to the client could be a security risk.
2. Keeping the client payload small will also lead to faster page load times.

**Comment by kennylavender** [comment]
> Revealing all the feature data to the client could be a security risk.

Good point, notes to self:
- Exposing names of disabled features to the client is probably not a good idea.
- The features may have additional keys of information that the application uses that shouldn't be exposed to the client.

If I haven't thought of anything better by tomorrow morning, I will re-open @nlambert's branch and pr.

**Comment by kennylavender** [comment]
I don't think I am going to think of anything better. I am coming around to the idea of the function. Reopened PR #71
