### ISSUE TITLE
Confusing withFeatures example code

### ISSUE THREAD

**Issue by ericelliott** [paralleldrive/react-feature-toggles#96]
Is my brain broken, or does this example make no sense?

```js
const Features = (withFeatures = { initialFeatures: [] }());

const Wrapper = () => <Features query={query} />;
```

**Comment by kennylavender** [comment]
Your brain is not broken.

Looks like a confusing example and it looks like prettier may have gotten a hold of it cause I don't remember that looking like that haha

**Comment by ericelliott** [comment]
Let's nuke it! 🔥 

🍰

**Comment by kennylavender** [comment]
woops forgot to tag this issue in #97
